DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS provider;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE provider (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  organizer_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  service_type TEXT NOT NULL,
  phone TEXT NOT NULL,
  FOREIGN KEY (organizer_id) REFERENCES user (id)
);